/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 17 december 2019
 * Author: Marc de Hoogh
 */

const mongoose=require('mongoose');

const userSchema=mongoose.Schema({
                                  name:{type:mongoose.Schema.Types.String,unique:true,minlength:1},
                                  password:{type:mongoose.Schema.Types.String,minlength:1},
                                 });
module.exports=userSchema;
